"""Shared markdown-to-HTML rendering with sanitization.

Provides a single conversion function used by all API endpoints
that return user-facing content generated by LLMs. Content is
stored as raw markdown in the database and rendered to safe HTML
at response time.
"""

from __future__ import annotations

import bleach
import markdown

ALLOWED_TAGS: list[str] = [
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "p",
    "strong",
    "em",
    "ul",
    "ol",
    "li",
    "br",
    "hr",
    "blockquote",
    "pre",
    "code",
    "table",
    "thead",
    "tbody",
    "tr",
    "th",
    "td",
]


def _strip_code_fences(text: str) -> str:
    """Remove wrapping backtick fences that LLMs sometimes add around entire responses.

    Gemini occasionally wraps its whole output in a ```markdown ... ``` or ``` ... ```
    fence. This strips those outer fences while preserving any intentional inline
    code spans. Only removes fences that wrap the entire content.
    """
    import re

    stripped = text.strip()
    # Match an optional language tag after the opening fence (e.g. ```markdown)
    fence_pattern = re.compile(r"^```[a-zA-Z]*\n(.*)\n```$", re.DOTALL)
    match = fence_pattern.match(stripped)
    if match:
        return match.group(1)
    return text


def render_markdown(raw: str | None) -> str | None:
    """Convert raw markdown to sanitized HTML.

    Returns None if input is None or empty.
    """
    if not raw:
        return None
    cleaned = _strip_code_fences(raw)
    raw_html = markdown.markdown(cleaned, extensions=["tables"])
    return bleach.clean(raw_html, tags=ALLOWED_TAGS, attributes={"th": ["align"], "td": ["align"]}, strip=True)
