"""Shared markdown-to-HTML rendering with sanitization.

Provides a single conversion function used by all API endpoints
that return user-facing content generated by LLMs. Content is
stored as raw markdown in the database and rendered to safe HTML
at response time.
"""

from __future__ import annotations

import bleach
import markdown

ALLOWED_TAGS: list[str] = [
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "p",
    "strong",
    "em",
    "ul",
    "ol",
    "li",
    "br",
    "hr",
    "blockquote",
    "pre",
    "code",
    "table",
    "thead",
    "tbody",
    "tr",
    "th",
    "td",
]


def render_markdown(raw: str | None) -> str | None:
    """Convert raw markdown to sanitized HTML.

    Returns None if input is None or empty.
    """
    if not raw:
        return None
    raw_html = markdown.markdown(raw)
    return bleach.clean(raw_html, tags=ALLOWED_TAGS, strip=True)
