<!--
  Admin Briefings View - Briefing management

  Admin interface for managing manager briefings including
  viewing generated content and briefing status.
-->
<script lang="ts">
  import { onMount } from "svelte";
  import { api } from "../lib/api";

  interface Briefing {
    id: number;
    team_name: string;
    date: string;
    content: string;
    is_viewed: boolean;
    created_at: string;
  }

  let briefings = $state<Briefing[]>([]);
  let loading = $state(false);
  let error = $state<string | null>(null);
  let selectedWeek = $state(0);
  let maxWeek = $state(1);
  let history = $state<number[]>([]);
  let editingBriefing = $state<Briefing | null>(null);
  let editContent = $state("");
  let saving = $state(false);
  let regeneratingId = $state<number | null>(null);
  let successMessage = $state<string | null>(null);

  /**
   * Fetches the recap history and league status to know which weeks to show.
   */
  async function loadHistory() {
    try {
      const [historyData, league]: [number[], any] = await Promise.all([
        api.get<number[]>("/recaps/history"),
        api.get("/league/info"),
      ]);

      history = historyData;
      // Admin should see at least current week, or further if they've been testing
      const historicalMax = history.length > 0 ? Math.max(...history) : 0;
      maxWeek = Math.max(league.current_week || 1, historicalMax);

      if (history.length > 0) {
        selectedWeek = history[0];
      } else {
        selectedWeek = maxWeek;
      }
    } catch {
      selectedWeek = 1;
    }
  }

  /**
   * Fetches the daily briefings across all franchises generated by the AI
   */
  async function loadBriefings(weekOverride?: number) {
    if (weekOverride !== undefined) {
      selectedWeek = weekOverride;
    }
    loading = true;
    error = null;
    try {
      // Pass week parameter to filter briefings by week
      const weekParam = selectedWeek > 0 ? selectedWeek : undefined;
      const url = weekParam
        ? `/admin/briefings?week=${weekParam}`
        : "/admin/briefings";
      briefings = await api.get<Briefing[]>(url);
    } catch (e: any) {
      error = e.message;
    } finally {
      loading = false;
    }
  }

  /**
   * Submits the administrator's manual markdown edits for a briefing back to the server.
   * Updates the localized state on success without requiring a full refetch.
   */
  async function saveEdit() {
    if (!editingBriefing) return;
    saving = true;
    try {
      await api.put(`/admin/briefings/${editingBriefing.id}`, {
        content: editContent,
      });
      const idx = briefings.findIndex((b) => b.id === editingBriefing!.id);
      if (idx !== -1)
        briefings[idx] = { ...briefings[idx], content: editContent };
      editingBriefing = null;
      editContent = "";
    } catch (e: any) {
      error = e.message;
    } finally {
      saving = false;
    }
  }

  /**
   * Forces a regeneration of an individual AI briefing using the LLM APIs asynchronously.
   * @param {number} briefingId - ID of the target briefing to regenerate
   */
  async function regenerate(briefingId: number) {
    regeneratingId = briefingId;
    error = null;
    try {
      await api.post(`/admin/briefings/${briefingId}/regenerate`);
      successMessage = "Regeneration queued — refresh in a moment";
      setTimeout(() => (successMessage = null), 5000);
      await loadBriefings();
    } catch (e: any) {
      error = e.message;
    } finally {
      regeneratingId = null;
    }
  }

  function startEdit(briefing: Briefing) {
    editingBriefing = briefing;
    editContent = briefing.content;
  }

  function cancelEdit() {
    editingBriefing = null;
    editContent = "";
  }

  function formatTs(ts: string) {
    return new Date(ts).toLocaleString();
  }

  onMount(async () => {
    await loadHistory();
    await loadBriefings();
  });
</script>

<div class="grid grid-cols-1 lg:grid-cols-[1fr_220px] gap-6">
  <!-- Main Content - Order 1 on mobile, 2 on desktop -->
  <main class="order-2 lg:order-1 min-w-0">
    {#if successMessage}
      <div
        class="card p-4 mb-4 border-l-4 border-l-(--color-success) font-mono text-xs text-(--color-success)"
      >
        {successMessage}
      </div>
    {/if}

    {#if error}
      <div
        class="card p-4 mb-4 border-l-4 border-l-(--color-danger) font-mono text-xs text-(--color-danger)"
      >
        {error}
      </div>
    {/if}

    {#if loading}
      <div class="space-y-4">
        {#each [1, 2, 3] as _}
          <div class="skeleton h-28 w-full rounded-sm"></div>
        {/each}
      </div>
    {:else if briefings.length === 0}
      <div class="card p-8 text-center">
        <p class="font-mono text-sm text-(--color-text-muted)">
          // NO BRIEFINGS DETECTED //
        </p>
      </div>
    {:else}
      <div class="space-y-4">
        {#each briefings as b (b.id)}
          <div class="card overflow-hidden">
            <div
              class="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3 p-4 border-b border-(--color-border-subtle)"
            >
              <div class="min-w-0">
                <div class="flex flex-wrap items-center gap-2 mb-1">
                  <span
                    class="font-mono text-xs font-bold tracking-widest uppercase text-(--color-text)"
                  >
                    MANAGER: {b.team_name}
                  </span>
                  <span
                    class="border-2 px-2 py-0.5 font-mono text-[10px] font-bold uppercase tracking-widest {b.is_viewed
                      ? 'bg-(--color-success-muted) text-(--color-success) border-(--color-success)'
                      : 'bg-(--color-warning-muted) text-(--color-warning) border-(--color-warning)'}"
                  >
                    {b.is_viewed ? "UNLOCKED BY MANAGER" : "UNREAD"}
                  </span>
                </div>
                <div
                  class="font-mono text-[0.55rem] text-(--color-text-muted) flex flex-wrap gap-2"
                >
                  <span>[DATE: {b.date}]</span>
                  <span>[TS: {formatTs(b.created_at)}]</span>
                </div>
              </div>

              <div class="flex gap-2 shrink-0">
                <button
                  onclick={() => startEdit(b)}
                  class="btn btn-secondary text-xs"
                >
                  EDIT
                </button>
                <button
                  onclick={() => regenerate(b.id)}
                  disabled={regeneratingId === b.id}
                  class="btn btn-primary text-xs"
                >
                  {regeneratingId === b.id ? "REGENERATING..." : "REGENERATE"}
                </button>
              </div>
            </div>

            <div class="p-4">
              {#if editingBriefing?.id === b.id}
                <div class="space-y-3">
                  <textarea
                    bind:value={editContent}
                    class="input w-full font-mono text-xs"
                    placeholder="Briefing content..."
                  ></textarea>
                  <div class="flex gap-2 justify-end">
                    <button
                      onclick={saveEdit}
                      disabled={saving}
                      class="btn btn-primary text-xs"
                    >
                      {saving ? "SAVING..." : "SAVE"}
                    </button>
                    <button
                      onclick={cancelEdit}
                      disabled={saving}
                      class="btn btn-secondary text-xs"
                    >
                      CANCEL
                    </button>
                  </div>
                </div>
              {:else if b.content}
                <div class="relative">
                  <div class="hidden"></div>
                  <div class="prose prose-sm min-w-0">
                    {@html b.content}
                  </div>
                </div>
              {:else}
                <p class="font-mono text-xs text-(--color-danger)">
                  [!] NO CONTENT — FATAL GENERATION ERROR
                </p>
              {/if}
            </div>
          </div>
        {/each}
      </div>
    {/if}
  </main>

  <!-- Archive Sidebar - Order 2 on mobile, 1 on desktop -->
  <aside class="order-1 lg:order-2">
    <div class="mb-3">
      <h3
        class="font-mono text-xs font-bold tracking-widest uppercase text-(--color-text-muted)"
      >
        ACTIVE WEEK
      </h3>
    </div>

    <div class="grid grid-cols-4 sm:grid-cols-6 lg:grid-cols-3 gap-1.5">
      {#each Array.from({ length: maxWeek }, (_, i) => i + 1) as w}
        {@const hasHistory = history.includes(w)}
        <button
          onclick={() => loadBriefings(w)}
          class="aspect-square flex flex-col items-center justify-center font-mono transition-all duration-200 group border-2 relative cursor-pointer
          {selectedWeek === w
            ? 'bg-(--color-accent-primary) text-(--color-text-inverse) border-(--color-accent-amber) shadow-[2px_2px_0px_rgba(100,255,100,0.2)]'
            : hasHistory
              ? 'bg-(--color-surface) text-(--color-text-commissioner) border-(--color-text) hover:border-(--color-accent-amber) hover:bg-(--color-surface-raised)'
              : 'bg-(--color-surface-base) text-(--color-text-muted) border-(--color-border-subtle) hover:border-(--color-border) hover:text-(--color-text-muted)'}"
          title="Week {w}"
        >
          <span class="text-xs font-bold">#{w.toString().padStart(2, "0")}</span
          >
          {#if hasHistory && selectedWeek !== w}
            <div
              class="absolute bottom-1 left-1/2 -translate-x-1/2 h-1 w-1 rounded-full bg-(--color-success)"
            ></div>
          {/if}
        </button>
      {/each}
    </div>

    <div class="mt-3">
      <p
        class="font-mono text-[0.55rem] text-(--color-text-muted) leading-relaxed"
      >
        DAILY BRIEFINGS AUDIT LOG. SELECT WEEK TO ALIGN BRIEFING FEED WITH
        PERFORMANCE METRICS.
      </p>
    </div>
  </aside>
</div>
