"""initial_final_state

Revision ID: 56aba76fca58
Revises:
Create Date: 2026-03-07 03:14:30.569206

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56aba76fca58"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commissioner_notification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("is_read", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "league",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("yahoo_league_key", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("num_teams", sa.Integer(), nullable=False),
        sa.Column("scoring_type", sa.Text(), nullable=False),
        sa.Column("current_week", sa.Integer(), nullable=True),
        sa.Column("start_week", sa.Integer(), nullable=True),
        sa.Column("end_week", sa.Integer(), nullable=True),
        sa.Column("stat_categories", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("roster_positions", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("yahoo_league_key"),
    )
    op.create_table(
        "player",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("yahoo_player_key", sa.Text(), nullable=False),
        sa.Column("yahoo_player_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("primary_position", sa.Text(), nullable=False),
        sa.Column("eligible_positions", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("mlb_id", sa.Integer(), nullable=True),
        sa.Column("lahman_id", sa.Text(), nullable=True),
        sa.Column("team_abbr", sa.Text(), nullable=True),
        sa.Column("bats", sa.Text(), nullable=True),
        sa.Column("throws", sa.Text(), nullable=True),
        sa.Column("is_pitcher", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("yahoo_rank", sa.Integer(), nullable=True),
        sa.Column("injury_status", sa.Text(), nullable=True),
        sa.Column("injury_note", sa.Text(), nullable=True),
        sa.Column("injury_updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("expected_return_date", sa.Date(), nullable=True),
        sa.Column("missed_games_count", sa.Integer(), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("yahoo_player_key"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("yahoo_guid", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), server_default="manager", nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_login", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("yahoo_guid"),
    )
    op.create_table(
        "free_agent_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("league_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("snapshot_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_available", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["league.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "player_mapping",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("yahoo_player_key", sa.Text(), nullable=False),
        sa.Column("mlb_id", sa.Integer(), nullable=True),
        sa.Column("lahman_id", sa.Text(), nullable=True),
        sa.Column("source_confidence", sa.Float(), server_default="1.0", nullable=False),
        sa.Column("auto_mapped", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("status", sa.Text(), server_default="confirmed", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["yahoo_player_key"],
            ["player.yahoo_player_key"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "player_value_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("category_scores", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("composite_value", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("yahoo_rank", sa.Integer(), nullable=True),
        sa.Column("our_rank", sa.Integer(), nullable=True),
        sa.Column("injury_weight", sa.Numeric(precision=3, scale=2), server_default="1.0", nullable=False),
        sa.Column("xwoba", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("xera", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("roster_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("roster_trend", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "snapshot_date", "type"),
    )
    op.create_table(
        "projection_baseline",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("projected_stats", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "source", "season"),
    )
    op.create_table(
        "session_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stat_line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("game_date", sa.Date(), nullable=False),
        sa.Column("game_datetime_utc", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("game_id", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("is_pitcher", sa.Boolean(), nullable=False),
        sa.Column("runs", sa.Integer(), nullable=True),
        sa.Column("home_runs", sa.Integer(), nullable=True),
        sa.Column("rbi", sa.Integer(), nullable=True),
        sa.Column("stolen_bases", sa.Integer(), nullable=True),
        sa.Column("batting_avg", sa.Numeric(precision=5, scale=3), nullable=True),
        sa.Column("hits", sa.Integer(), nullable=True),
        sa.Column("at_bats", sa.Integer(), nullable=True),
        sa.Column("wins", sa.Integer(), nullable=True),
        sa.Column("saves", sa.Integer(), nullable=True),
        sa.Column("strikeouts", sa.Integer(), nullable=True),
        sa.Column("era", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("whip", sa.Numeric(precision=5, scale=3), nullable=True),
        sa.Column("innings_pitched", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("earned_runs", sa.Integer(), nullable=True),
        sa.Column("walks", sa.Integer(), nullable=True),
        sa.Column("extra_stats", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "game_date", "source"),
    )
    op.create_table(
        "team",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("league_id", sa.Integer(), nullable=False),
        sa.Column("yahoo_team_key", sa.Text(), nullable=False),
        sa.Column("yahoo_manager_guid", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("manager_user_id", sa.Integer(), nullable=True),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("wins", sa.Integer(), server_default="0", nullable=False),
        sa.Column("losses", sa.Integer(), server_default="0", nullable=False),
        sa.Column("ties", sa.Integer(), server_default="0", nullable=False),
        sa.Column("standing", sa.Integer(), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["league.id"],
        ),
        sa.ForeignKeyConstraint(
            ["manager_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("yahoo_team_key"),
    )
    op.create_index(op.f("ix_team_yahoo_manager_guid"), "team", ["yahoo_manager_guid"], unique=False)
    op.create_table(
        "yahoo_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("access_token_encrypted", sa.Text(), nullable=False),
        sa.Column("refresh_token_encrypted", sa.Text(), nullable=False),
        sa.Column("encryption_key_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "manager_briefing",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_viewed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "matchup",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("league_id", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("team_a_id", sa.Integer(), nullable=False),
        sa.Column("team_b_id", sa.Integer(), nullable=False),
        sa.Column("team_a_stats", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("team_b_stats", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("category_results", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("team_a_wins", sa.Integer(), server_default="0", nullable=False),
        sa.Column("team_b_wins", sa.Integer(), server_default="0", nullable=False),
        sa.Column("ties", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_complete", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["league.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_a_id"],
            ["team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_b_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("league_id", "week", "team_a_id", "team_b_id"),
    )
    op.create_table(
        "recap",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("league_id", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.Text(), server_default="draft", nullable=False),
        sa.Column("stat_payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("model_used", sa.Text(), nullable=True),
        sa.Column("provider_used", sa.Text(), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("published_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["league.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roster_slot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Text(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "player_id", "season", "week", "position"),
    )
    op.create_table(
        "ai_usage_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("recap_id", sa.Integer(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["recap_id"],
            ["recap.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ai_usage_log")
    op.drop_table("roster_slot")
    op.drop_table("recap")
    op.drop_table("matchup")
    op.drop_table("manager_briefing")
    op.drop_table("yahoo_token")
    op.drop_index(op.f("ix_team_yahoo_manager_guid"), table_name="team")
    op.drop_table("team")
    op.drop_table("stat_line")
    op.drop_table("session_log")
    op.drop_table("projection_baseline")
    op.drop_table("player_value_snapshot")
    op.drop_table("player_mapping")
    op.drop_table("free_agent_snapshot")
    op.drop_table("users")
    op.drop_table("player")
    op.drop_table("league")
    op.drop_table("commissioner_notification")
    # ### end Alembic commands ###
